name: hot_spot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  dio: ^5.5.0+1
  drop_menu: ^0.0.6
  fan_floating_menu: ^0.0.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_open_street_map: ^0.0.4
  flutter_osm_interface: ^1.1.0
  flutter_osm_plugin: ^1.2.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  logger: ^2.4.0
  marquee: ^2.2.3
  permission_handler: ^11.3.1
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/hintergründe/
